Repository nim-works/phy, pull requests merged in 2024-10, with the labels that each got.

#49 source2il: simpler `Expr` rules
  passes/source2il.nim
Labels: refactor

#53 source2il: disallow using built-in name for declaration
  passes/source2il.nim
  spec/spec.md
  tests/expr/t06_redeclaration_error_3.test
Labels: bug, refactor

#50 lang: add expression lists
  passes/source2il.nim
  passes/spec_source.nim
  spec/spec.md
  tests/expr/t09_exprs_nested.test
  tests/expr/t09_exprs_nontrailing_non-unit-void_error copy.test
  tests/expr/t09_exprs_single_1.test
  tests/expr/t09_exprs_single_2.test
  tests/expr/t09_exprs_single_void.test
  tests/expr/t09_exprs_trailing_void.test
  tests/expr/t09_exprs_valid_nonvoid.test
  tests/expr/t09_exprs_valid_void.test
Labels: enhancement

#54 pass10: fix nested loop data-flow analysis
  passes/pass10.nim
  tests/pass10/t03_ssa_loop_4.expected
  tests/pass10/t03_ssa_loop_4.test
  tests/pass10/t03_ssa_loop_5.expected
  tests/pass10/t03_ssa_loop_5.test
  tests/pass10/t03_ssa_loop_6.expected
  tests/pass10/t03_ssa_loop_6.test
  tests/pass10/t03_ssa_loop_7.expected
  tests/pass10/t03_ssa_loop_7.test
Labels: bug

#46 lang: `If` expression support
  passes/source2il.nim
  passes/spec_source.nim
  phy/types.nim
  spec/spec.md
  tests/expr/t08_if_body_else_expr_mismatch.test
  tests/expr/t08_if_expr_both_void.test
  tests/expr/t08_if_expr_else_void.test
  tests/expr/t08_if_expr_then_void.test
  tests/expr/t08_if_expr_unify_type_1.test
  tests/expr/t08_if_expr_unify_type_2.test
  tests/expr/t08_if_false.test
  tests/expr/t08_if_not_a_predicate.test
  tests/expr/t08_if_only_body_not_unit.test
  tests/expr/t08_if_only_body_unit.test
  tests/expr/t08_if_only_body_void.test
  tests/expr/t08_if_true.test
  vm/utils.nim
Labels: enhancement

#47 spec: prepare for variables and parameters
  spec/spec.md
Labels: documentation

#57 vm: fix `opcBitNot` validation
  tests/vm/t04_bitnot.test
  vm/assembler.nim
  vm/vmvalidation.nim
Labels: bug, enhancement

#55 lang: add locals and assignments
  passes/source2il.nim
  passes/spec_source.nim
  spec/spec.md
  tests/expr/t09_asgn_compatible_type.test
  tests/expr/t09_asgn_field.test
  tests/expr/t09_asgn_incompatible_type_error.test
  tests/expr/t09_asgn_local.test
  tests/expr/t09_decl.test
  tests/expr/t09_decl_after_use_error.test
  tests/expr/t09_decl_no_self_visibility_error.test
  tests/expr/t09_decl_redeclaration_in_initializer_error.test
  tests/expr/t09_decl_void_error.test
  tests/expr/t09_exprs_eval_order_1.test
  tests/expr/t09_exprs_eval_order_2.test
  tests/expr/t10_asgn_eval_order_1.test
  tests/expr/t10_asgn_eval_order_2.test
  tests/expr/t10_asgn_eval_order_3.test
  tests/expr/t10_asgn_lhs_must_be_lvalue_1.test
  tests/expr/t10_asgn_lhs_must_be_lvalue_2.test
  tests/expr/t10_asgn_lhs_must_be_lvalue_3.test
  tests/expr/t10_asgn_lhs_must_be_lvalue_4_error.test
  tests/expr/t10_asgn_lhs_must_be_lvalue_5_error.test
  tests/expr/t10_asgn_lhs_must_be_lvalue_6_error.test
  tests/expr/t10_asgn_lhs_must_be_lvalue_7_error.test
  tests/expr/t11_scopes_if_1.test
  tests/expr/t11_scopes_if_2_error.test
  tests/expr/t11_scopes_local_cannot_shadow_error_1.test
  tests/expr/t11_scopes_local_cannot_shadow_error_2.test
  tests/expr/t11_scopes_procdef.test
Labels: enhancement

#58 pass0: fix `BitAnd` and `BitOr` translation
  passes/pass0.nim
  tests/pass0/t03_bitand.expected
  tests/pass0/t03_bitand.test
  tests/pass0/t03_bitor.expected
  tests/pass0/t03_bitor.test
Labels: bug

#59 pass4: fix `Rename` edge conflict resolution
  passes/pass4.nim
  tests/pass4/t03_rename_resolution_three_clusters.expected
  tests/pass4/t03_rename_resolution_three_clusters.test
  tests/pass4/t03_rename_resolution_two_subgraphs.test
Labels: bug

#61 add the `phy` CLI application
  common/vmexec.nim
  koch.nim
  passes/spec.nim
  passes/spec_source.nim
  passes/trees.nim
  phy/nim.cfg
  phy/phy.nim
  tests/pass0/runner.nim
Labels: enhancement

#63 tests: replace some custom runners with `phy`
  .github/workflows/build_and_test.yml
  phy/phy.nim
  tests/expr/runner.nim
  tests/expr/runner.txt
  tests/pass0/runner.nim
  tests/pass0/runner.txt
  tests/pass0/t03_loop.test
  tests/pass1/runner.nim
  tests/pass1/runner.txt
  tests/pass10/runner.nim
  tests/pass10/runner.txt
  tests/pass10/t01_loop.test
  tests/pass10/t01_unreachable.test
  tests/pass10/t03_ssa_loop_4.test
  tests/pass3/runner.nim
  tests/pass3/runner.txt
  tests/pass3/t03_at_indirect.test
  tests/pass3/t03_field_indirect.test
  tests/pass3/t04_load_aggregate.test
  tests/pass3/t04_store_aggregate.test
  tests/pass4/runner.nim
  tests/pass4/runner.txt
  tools/tester.nim
Labels: enhancement, refactor
