Repository nim-works/phy, pull requests merged in 2025-05, with the labels that each got.

#157 phy: instrument pass execution
  phy/phy.nim
  phy/tracing.nim
Labels: enhancement

#160 lang0: split `Conv` into multiple operators
  languages/lang0.md
  passes/pass0.nim
  passes/pass_aggregateParams.nim
  passes/syntax.nim
  skully/backend.nim
  tests/pass0/t03_demote_float64_to_float32.expected
  tests/pass0/t03_demote_float64_to_float32.test
  tests/pass0/t03_promote_float64_to_float32.expected
  tests/pass0/t03_promote_float64_to_float32.test
  tests/pass0/t03_sext_int_to_int.expected
  tests/pass0/t03_sext_int_to_int.test
  tests/pass0/t03_sext_int_to_uint.expected
  tests/pass0/t03_sext_int_to_uint.test
  tests/pass0/t03_sext_uint_to_int.expected
  tests/pass0/t03_sext_uint_to_int.test
  tests/pass0/t03_sext_uint_to_uint.expected
  tests/pass0/t03_sext_uint_to_uint.test
  tests/pass0/t03_trunc_int_to_int.expected
  tests/pass0/t03_trunc_int_to_int.test
  tests/pass0/t03_trunc_int_to_uint.expected
  tests/pass0/t03_trunc_int_to_uint.test
  tests/pass0/t03_trunc_uint_to_int.expected
  tests/pass0/t03_trunc_uint_to_int.test
  tests/pass0/t03_trunc_uint_to_uint.expected
  tests/pass0/t03_trunc_uint_to_uint.test
  tests/pass0/t03_zext_int_to_int.expected
  tests/pass0/t03_zext_int_to_int.test
  tests/pass0/t03_zext_int_to_uint.expected
  tests/pass0/t03_zext_int_to_uint.test
  tests/pass0/t03_zext_uint_to_int.expected
  tests/pass0/t03_zext_uint_to_int.test
  tests/pass0/t03_zext_uint_to_uint.expected
  tests/pass0/t03_zext_uint_to_uint.test
Labels: enhancement

#161 pass0: clean up and improve documentation
  passes/pass0.nim
Labels: refactor

#162 README with bare bones build instructions
  README.md
Labels: documentation

#163 ci: read NimSkull version from file
  .github/workflows/build_and_test.yml
  README.md
  nimskull.version
Labels: refactor

#166 disasm: fix output for constants
  tests/pass0/t03_demote_float64_to_float32.expected
  vm/disasm.nim
Labels: bug

#169 koch: replace `single` and `all` with `build`
  .github/workflows/build_and_test.yml
  README.md
  koch.nim
Labels: enhancement

#168 vmmodules: add support for module memory
  phy/phy.nim
  phy/repl.nim
  phy/vmexec.nim
  tests/vm/t08_relocation.test
  tests/vm/t09_init.test
  vm/assembler.nim
  vm/disasm.nim
  vm/vmalloc.nim
  vm/vmmodules.nim
  vm/vmvalidation.nim
Labels: bug, enhancement

#170 add an IL with global locations
  languages/lang0.md
  languages/lang25.md
  languages/lang6.md
  passes/pass0.nim
  passes/pass25.nim
  passes/pass_globalsToPointer.nim
  passes/syntax.nim
  phy/phy.nim
  phy/repl.nim
  tests/pass0/t05_data_init.expected
  tests/pass0/t05_data_init.test
  tests/pass0/t05_data_layout.expected
  tests/pass0/t05_data_layout.test
  tests/pass0/t05_data_uninit.expected
  tests/pass0/t05_data_uninit.test
  tests/passes/globals_to_pointer/addr.expected
  tests/passes/globals_to_pointer/addr.test
  tests/passes/globals_to_pointer/asgn.expected
  tests/passes/globals_to_pointer/asgn.test
  tests/passes/globals_to_pointer/copy.expected
  tests/passes/globals_to_pointer/copy.test
  tests/passes/globals_to_pointer/globals.expected
  tests/passes/globals_to_pointer/globals.test
  tests/passes/globals_to_pointer/runner.txt
Labels: enhancement

#171 use global locations instead of pointer constants
  passes/source2il.nim
  phy/vmexec.nim
  skully/backend.nim
Labels: refactor

#172 add an IL with a dedicated pointer type
  languages/lang1.md
  languages/lang3.md
  languages/langPtr.md
  passes/pass_aggregateParams.nim
  passes/pass_aggregatesToBlob.nim
  passes/pass_globalsToPointer.nim
  passes/pass_legalizeBlobOps.nim
  passes/pass_localsToBlob.nim
  passes/pass_ptrToInt.nim
  passes/pass_stackAlloc.nim
  passes/source2il.nim
  passes/syntax.nim
  phy/phy.nim
  phy/repl.nim
  phy/type_rendering.nim
  phy/types.nim
  phy/vmexec.nim
  skully/backend.nim
  tests/passes/aggregate_params/aggregate_parameters.expected
  tests/passes/aggregate_params/call_argument_hoisting.expected
  tests/passes/aggregate_params/operand_hoisting.expected
  tests/passes/aggregate_params/path_operand_hoisting.expected
  tests/passes/aggregate_params/return_aggregate.expected
  tests/passes/blobs/paths.expected
  tests/passes/globals_to_pointer/addr.expected
  tests/passes/globals_to_pointer/asgn.expected
  tests/passes/globals_to_pointer/copy.expected
  tests/passes/globals_to_pointer/globals.expected
  tests/passes/pointers/offset.expected
  tests/passes/pointers/offset.test
  tests/passes/pointers/reinterpret.expected
  tests/passes/pointers/reinterpret.test
  tests/passes/pointers/runner.txt
  tests/passes/pointers/types.expected
  tests/passes/pointers/types.test
  tests/passes/stack_alloc/id_patching.expected
  tests/passes/stack_alloc/layout.expected
Labels: enhancement, refactor

#173 skully: fix various bugs
  skully/backend.nim
Labels: bug

#175 source2il: implement `CharTy` support
  languages/specification.md
  passes/source2il.nim
  tests/expr/t05_char_type.nim
Labels: bug

#176 source2il: fix crash when copying records
  passes/source2il.nim
  phy/types.nim
  tests/expr/t17_seq_copy_6.test
Labels: bug

#177 source2il: fix crashes with erroneous code
  passes/source2il.nim
  phy/type_rendering.nim
  tests/errors/README.md
  tests/errors/terror_in_call_argument.test
  tests/errors/terror_in_if_1.test
  tests/errors/terror_in_if_2.test
  tests/errors/terror_in_tuple_cons.test
Labels: bug
